import pandas as pd
from pathlib import Path
import chromadb
from chromadb.utils import embedding_functions
from groq import Groq
import os
from dotenv import load_dotenv

load_dotenv()


chromadb_client = chromadb.PersistentClient()
groq_client = Groq()

ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

RETRIEVAL_THRESHOLD = 0.7


def ingest_faq_data(path):
    if "faqs" not in chromadb_client.list_collections():

        collection = chromadb_client.get_or_create_collection(
            name="faqs",
            embedding_function=ef,
            metadata={
                "hnsw:space": "cosine"
            },  # Hierarchical Navigable Small World(it is vector search indexing algorithm). values: cosine for cosine similarity, l2 for euclidean distance/raw geometric distance(default setting), ip for inner product(when vectors are already normalized).
        )

        df = pd.read_csv(path)
        docs = df["question"].tolist()

        collection.add(
            documents=docs,
            ids=[f"faqid_{i}" for i in range(len(docs))],
            metadatas=[{"answer": ans} for ans in df["answer"].to_list()],
        )

    else:
        print(f"Collection: 'faqs' already exist")


def retrieve_faqs(query):
    """
    Takes a user query and retrieves the top matching records from the ChromaDB collection,
    returning a dictionary like object containing ids, documents, metadatas, and distances.
    """
    collection = chromadb_client.get_collection(name="faqs", embedding_function=ef)
    result = collection.query(query_texts=[query], n_results=3)
    return result


def generate_grounded_answer(query, context):
    prompt = f"""Given the following context and question, generate answer based on this context only.
    If the answer is not found in the context, kindly state "I don't know". Don't try to make up an answer.
    
    CONTEXT: {context}
    
    QUESTION: {query}
    """

    chat_completion = groq_client.chat.completions.create(
        messages=[
            # Set an optional system message. This sets the behavior of the
            # assistant and can be used to provide specific instructions for
            # how it should behave throughout the conversation.
            {
                "role": "system",
                "content": "You are a helpful and friendly Flipkart(ecommerce company) assistant.",
            },
            # Set a user message for the assistant to respond to.
            {
                "role": "user",
                "content": prompt,
            },
        ],
        # The language model which will generate the completion.
        model=os.environ["GROQ_MODEL"],
    )

    return chat_completion.choices[0].message.content


def faq_rag_pipeline(query):
    """Main function that takes user query from the frontend, retrieves relevant FAQ answers from ChromaDB,
    and generates a final answer using Groq LLM."""

    result = retrieve_faqs(query)  # retrieves relevant FAQ answers from ChromaDB

    best_distance = result["distances"][0][0]
    if (
        best_distance > RETRIEVAL_THRESHOLD
    ):  # Retrival threshold: If the best distance is greater than 0.7, it means that the retrieved FAQ answers are not relevant enough to the user query, and we can return "I don't know" without touching the llm.

        return {
            "answer": "I don't know",
            "metadata": {
                "source": "Threshold failed. No relevant FAQ found in the database.",
                "distance": best_distance
            }
        }

    context = "\n".join(
        [x.get("answer") for x in result["metadatas"][0]]
    )  # concatenates the retrieved FAQ answers to create a context for the LLM

    final_answer = generate_grounded_answer(query, context)
    return  {
            "answer": final_answer,
            "metadata": {
                "source": "Threshold passed. Generated by LLM.",
                "distance": best_distance
            }
        }


if __name__ == "__main__":

    print("\n=== Testing Ingestion ===")
    faqs_path = Path(__file__).parent / "resources" / "faq_data.csv"
    ingest_faq_data(faqs_path)

    query = "What's your policy on defective products?"
    #query = "How do I apply for a home loan?"
    
    print("\n=== Testing Retrieval ===") 
    retrieval_result = retrieve_faqs(query)
    print("\nIDs:")
    print(retrieval_result["ids"])
    print("\nDocuments:")
    print(retrieval_result["documents"])
    print("\nMetadatas:")
    print(retrieval_result["metadatas"])
    print("\nDistances:")
    print(retrieval_result["distances"])

    print("\n=== Testing Threshold ===")
    best_distance = retrieval_result["distances"][0][0]
    print(f"Best Distance: {best_distance}")
    if best_distance > RETRIEVAL_THRESHOLD:
        print("Threshold Failed")
    else:
        print("Threshold Passed")

    print("\n=== Testing Context Creation ===")
    context = "\n\n".join([x["answer"] for x in retrieval_result["metadatas"][0]])
    print(context)

    print("\n=== Testing LLM Generation ===")
    answer = generate_grounded_answer(query, context)
    print(answer)

    print("\n=== Testing Full RAG Pipeline ===")
    
    query = "When will I get my money back?"
    final_answer = faq_rag_pipeline(query)
    print(f"{query} : {final_answer}")
    
    query = "How do I apply for a home loan?"
    final_answer = faq_rag_pipeline(query)
    print(f"{query} : {final_answer}")

    query = "When is the cricket match between India and Pakistan?"
    final_answer = faq_rag_pipeline(query)
    print(f"{query} : {final_answer}")


    #Distance calibration: testing retrieval distances for different queries.
    test_queries = [
        "What is your return policy?",
        "Can I return a damaged product?",
        "How long do refunds take?",
        "How do I apply for a home loan?",
        "How to become a pilot?",
        "How to open a flipkart account?",
        "When is the cricket match between India and Pakistan?",
    ]

    print("\n=== Distance Calibration ===")
    for query_text in test_queries:
        result = retrieve_faqs(query_text)
        print(f"{query_text} -> {result['distances'][0][0]}")

    